import React, { useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowUpRight, ArrowRight, Instagram, MessageCircle, Menu, X, Heart, Sparkles, ShoppingBag, Check, Copy } from 'lucide-react'
import './styles.css'

const whatsapp = 'https://wa.me/message/UYRBMHAN7V52O1'
const instagram = 'https://www.instagram.com/usekorabel/'
const products = [
  {name:'Vestido com franzido',color:'Pink',category:'Vestidos',image:'06775c687ea9d759',post:'Dbs6uLTDpGk'},
  {name:'Vestido de um ombro só',color:'Nude',category:'Vestidos',image:'83e8c4aef71bcaff',post:'Dbs6d8WDk7L'},
  {name:'Vestido ombro a ombro',color:'Amarelo',category:'Vestidos',image:'4dfbb7aa933bbe95',post:'Dbs6ITkDgYw'},
  {name:'Look frente única',color:'Preto',category:'Conjuntos',image:'7f5372a4e051bb4e',post:'Dbs5uYeDjld'},
]
const photo = p => `/images/${p.image}.jpg`
function Brand(){return <a className="brand" href="#inicio" aria-label="Korabel — início"><img src="/images/logo.jpg" alt="Korabel Modas" width="66" height="66"/><span>KORABEL<small>M O D A S</small></span></a>}
function WhatsLink({children,className=''}){return <a className={className} aria-label={className==='nav-cta'?'Falar com a Korabel no WhatsApp':undefined} href={whatsapp} target="_blank" rel="noopener noreferrer">{children}</a>}
function ProductCard({product}){const [copied,setCopied]=useState(false);async function copy(){try{await navigator.clipboard.writeText(`Olá, Korabel! Tenho interesse no ${product.name.toLowerCase()} (${product.color}). Poderiam informar valor e tamanhos disponíveis? https://www.instagram.com/usekorabel/p/${product.post}/`);setCopied(true)}catch{setCopied(false)}}return <article className="product"><a className="product-photo" href={`https://www.instagram.com/usekorabel/p/${product.post}/`} target="_blank" rel="noopener noreferrer" aria-label={`Ver ${product.name} no Instagram`}><img src={photo(product)} alt={`${product.name} na cor ${product.color}, apresentado pela Korabel`} loading="lazy" width="559" height="640"/><span className="photo-label">KORABEL SELECTION</span><span className="photo-arrow"><ArrowUpRight size={19}/></span></a><div className="product-meta"><span>{product.category}</span><span>{product.color}</span></div><h3>{product.name}</h3><p className="price">Valor e tamanhos sob consulta</p><WhatsLink className="product-button">Consultar no WhatsApp <ArrowUpRight size={17}/></WhatsLink><button className="copy-button" onClick={copy}>{copied?<Check size={13}/>:<Copy size={13}/>}<span aria-live="polite">{copied?'Mensagem copiada! Cole na conversa':'Copiar mensagem sobre esta peça'}</span></button></article>}
function App(){const [menu,setMenu]=useState(false);const [filter,setFilter]=useState('Todos');return <>
  <div className="announcement">Looks para viver sua melhor versão <span>♡</span><a href={instagram} target="_blank" rel="noopener noreferrer">Conheça @usekorabel <ArrowUpRight size={13}/></a></div>
  <header><div className="nav-wrap"><Brand/><nav aria-label="Menu principal" className={menu?'open':''}>{[['Início','inicio'],['Nossos looks','looks'],['A Korabel','sobre'],['Como comprar','como-comprar']].map(([label,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{label}</a>)}</nav><WhatsLink className="nav-cta"><MessageCircle size={18}/><span>Fale com a gente</span></WhatsLink><button className="menu-toggle" aria-label={menu?'Fechar menu':'Abrir menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
  <main>
    <section className="hero" id="inicio"><div className="hero-inner"><div className="hero-copy"><div className="eyebrow"><span/> MODA FEMININA · KORABEL</div><h1>Seu estilo.<br/>Sua essência.<br/><em>Sua melhor versão.</em></h1><p>Looks que acompanham quem você é.<br/>Descubra peças para se sentir linda,<br className="desktop-break"/> confiante e do seu jeito.</p><a className="button primary" href="#looks">Encontre seu próximo look <ArrowRight size={18}/></a><div className="hero-note"><Heart size={16}/> Um toque de charme em cada escolha.</div></div><div className="hero-visual"><div className="hero-frame back"><img src={photo(products[0])} alt="Vestido pink com franzido da Korabel" width="559" height="640"/></div><div className="hero-frame front"><img src={photo(products[1])} alt="Vestido nude de um ombro só da Korabel" width="559" height="640" fetchPriority="high"/></div><span className="collection-note">feito para<br/><em>ser você.</em></span><a className="hero-caption" href="#looks">Explore a seleção <ArrowUpRight size={20}/></a></div></div><div className="hero-bottom"><span>ESTILO QUE ENCANTA. ATITUDE QUE INSPIRA.</span><span>DESCUBRA A KORABEL <ArrowRight size={16}/></span></div></section>
    <div className="benefits container"><div><Sparkles/><span>Moda com personalidade<small>Looks que expressam seu estilo</small></span></div><div><MessageCircle/><span>Vamos conversar?<small>Atendimento pelo WhatsApp</small></span></div><div><ShoppingBag/><span>Sua escolha, do seu jeito<small>Consulte detalhes antes de pedir</small></span></div></div>
    <section className="collection container" id="looks"><div className="section-top"><div><span className="eyebrow">ESCOLHA O SEU FAVORITO</span><h2>Um look. <em>Mil possibilidades.</em></h2></div><p>Do delicado ao marcante.<br/>Qual combina com você hoje?</p></div><div className="filters" aria-label="Filtrar peças">{['Todos','Vestidos','Conjuntos'].map(f=><button key={f} onClick={()=>setFilter(f)} aria-pressed={filter===f} className={filter===f?'active':''}>{f}</button>)}<span>Direto do nosso Instagram <Instagram size={15}/></span></div><div className="products">{products.filter(p=>filter==='Todos'||p.category===filter).map(p=><ProductCard key={p.post} product={p}/>)}</div><p className="collection-foot">Gostou de uma peça? Confirme valor, tamanhos e disponibilidade com a gente.</p></section>
    <section className="about container" id="sobre"><div className="about-picture"><img src={photo(products[2])} alt="Look amarelo ombro a ombro da coleção Korabel" loading="lazy" width="559" height="640"/><div className="about-tag">mais que um look,<br/><em>uma forma de se expressar.</em></div></div><div className="about-copy"><span className="eyebrow">PRAZER, SOMOS A KORABEL</span><h2>A beleza de<br/>ser <em>você mesma.</em></h2><p>Tem dias que pedem leveza. Outros, uma dose extra de atitude. Na Korabel, a moda feminina é um convite para explorar todas as suas versões.</p><p>Entre cores, detalhes e diferentes estilos, encontre aquele look que tem a sua cara. Conheça nossas peças por aqui e converse com a gente para escolher a sua.</p><a className="text-link" href={instagram} target="_blank" rel="noopener noreferrer">Vem conhecer nosso universo <Instagram size={18}/></a><div className="signature">Com carinho, Korabel ♡</div></div></section>
    <section className="how-section" id="como-comprar"><div className="container"><span className="eyebrow">DO PRIMEIRO OLHAR AO SEU LOOK</span><h2>Se apaixonou? <em>É simples.</em></h2><div className="steps"><div><span className="step-number">01</span><h3>Encontre seu favorito</h3><p>Explore a vitrine e escolha a peça que combina com o seu momento.</p></div><div><span className="step-number">02</span><h3>Chame no WhatsApp</h3><p>Copie a mensagem da peça e envie na conversa. Consulte valor, tamanho e disponibilidade.</p></div><div><span className="step-number">03</span><h3>Combine os detalhes</h3><p>Confirme pagamento e opções de recebimento diretamente com a Korabel.</p></div></div></div></section>
    <section className="final-cta container"><span className="eyebrow">SEU PRÓXIMO LOOK COMEÇA AQUI</span><h2>Vamos encontrar o seu <em>favorito?</em></h2><p>Conte pra gente o que você procura. A conversa continua no WhatsApp.</p><WhatsLink className="button primary"><MessageCircle size={19}/> Falar com a Korabel <ArrowUpRight size={18}/></WhatsLink></section>
  </main><footer><div className="container footer-main"><div><Brand/><p>Moda feminina com estilo e atitude.<br/>Looks para viver sua melhor versão.</p></div><div><h3>Explore</h3><a href="#looks">Nossos looks</a><a href="#sobre">Sobre a Korabel</a><a href="#como-comprar">Como comprar</a></div><div><h3>Fique por perto</h3><a href={instagram} target="_blank" rel="noopener noreferrer"><Instagram size={16}/> @usekorabel</a><WhatsLink><MessageCircle size={16}/> Atendimento no WhatsApp</WhatsLink><span className="online-note">Vendas online</span></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Korabel Modas.</span><span>Seu estilo. Sua essência.</span></div></footer><WhatsLink className="floating-whatsapp"><span>Vamos conversar?</span><MessageCircle size={27}/><span className="sr-only">Abrir WhatsApp da Korabel</span></WhatsLink>
</>}
createRoot(document.getElementById('root')).render(<App/> )
